- name: Configure wavm
  hosts: wavm
  gather_facts: false
  pre_tasks:
    - name: Wait for PSRP listener to accept connections
      ansible.builtin.wait_for_connection:
        delay: 0
        sleep: 10
        timeout: 900
  roles:
    - role: ansible-role-user-access-windows
      user_access_username: LocalAdmin
      user_access_password: Password123!
      user_access_rdp: True
      user_access_admin: True
  tasks:
    - name: Install Git, Autopsy, and Strawberry Perl via Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name:
          - git
          - autopsy
          - strawberryperl
        state: present

    - name: Download CodeMeter runtime
      ansible.windows.win_get_url:
        url: https://github.com/sderziotis/btcmp-16-windows/releases/download/v1.3/CodeMeterRuntime.zip
        dest: C:\Windows\Temp\CodeMeterRuntime.zip

    - name: Extract CodeMeter runtime
      community.windows.win_unzip:
        src: C:\Windows\Temp\CodeMeterRuntime.zip
        dest: C:\Windows\Temp\CodeMeter

    - name: Install CodeMeter runtime silently
      ansible.windows.win_shell: |
        & "C:\Windows\Temp\CodeMeter\CodeMeterRuntime.exe" /ComponentArgs "*":"/qn"
      become: yes
      become_method: runas
      become_user: SYSTEM
      args:
        creates: C:\Program Files\CodeMeter\Runtime\bin\CodeMeter.exe

    - name: Download FTK Imager
      ansible.windows.win_get_url:
        url: https://github.com/sderziotis/btcmp-16-windows/releases/download/v1.3/FTK.Imager.zip
        dest: C:\Windows\Temp\FTKImager.zip

    - name: Ensure FTK Imager destination exists
      ansible.windows.win_file:
        path: C:\Tools\FTKImager
        state: directory

    - name: Extract FTK Imager
      community.windows.win_unzip:
        src: C:\Windows\Temp\FTKImager.zip
        dest: C:\Tools\FTKImager

    - name: Remove temp files
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\Windows\Temp\CodeMeterRuntime.zip
        - C:\Windows\Temp\CodeMeter
        - C:\Windows\Temp\FTKImager.zip

- name: Configure wvvm
  hosts: wvvm
  gather_facts: false
  pre_tasks:
    - name: Wait for PSRP listener to accept connections
      ansible.builtin.wait_for_connection:
        delay: 0
        sleep: 10
        timeout: 900
  roles:
    - role: ansible-role-user-access-windows
      user_access_username: LocalAdmin
      user_access_password: Password123!
      user_access_rdp: True
      user_access_admin: True